
export const categories = {
    TIME_SERIES_INTRADAY : 'TIME_SERIES_INTRADAY',
    TIME_SERIES_DAILY : 'TIME_SERIES_DAILY',
    TIME_SERIES_MONTHLY : 'TIME_SERIES_MONTHLY',
    ALPHA_INTELLIGENCE : 'ALPHA_INTELLIGENCE',
    FUNDAMENTAL: 'FUNDAMENTAL',
    PHYSICAL: 'PHYSICAL',
    COMMODITIES: 'COMMODITIES',
    ECONOMIC_INDICATORS: 'ECONOMIC_INDICATORS',
    TECHNICAL_INDICATORS: 'TECHNICAL_INDICATORS',
    CURRENCY_EXCHANGE_RATE: 'CURRENCY_EXCHANGE_RATE',
}